### ISSUE TITLE
NOT AN ISSUE 

### ISSUE THREAD

**Issue by spencerthayer** [dillbyrne/HashPass#5]
Just wanted to say we are kind of kindred spirits. I am doing the same thing in Javascript over at http://passcloud.me.

**Comment by dillbyrne** [comment]
Hi @spencerthayer 
 
TLS is a must if you are going to host a site to generate passwords for the user over the web https://letsencrypt.org/ will give you a free cert

**Comment by spencerthayer** [comment]
Yes https works for the site. I just typed http.

https://passcloud.me
